name: "cloud.gov deploy"
description: "Deploy application to cloud.gov using manifest file"
inputs:
  cf_api:
    description: "API endpoint for login"
    required: false
    default: "https://api.fr.cloud.gov"
  cf_username:
    description: "cloud.gov username for deploy user"
    required: true
  cf_password:
    description: "cloud.gov password for deploy user"
    required: true
  cf_org:
    description: "cloud.gov organization to deploy into"
    required: true
  cf_space:
    description: "cloud.gov space to deploy into"
    required: true
  app_directory:
    description: "directory to deploy"
    required: false
    default: "./"
  push_arguments:
    description: "additional command line arguments to pass to cf push"
    required: false
    default: ""
  full_command:
    description: "Full command with arguments to run instead of cf push"
    required: false
    default: "push"

runs:
  using: "composite"
  steps:
    - name: "Install cf-cli@7"
      shell: bash
      run: |
        curl -A "cg-deploy-action" -v -L -o cf-cli_amd64.deb 'https://packages.cloudfoundry.org/stable?release=debian64&version=v8&source=github'
        sudo dpkg -i cf-cli_amd64.deb

    - name: "Login to cf api"
      shell: bash
      env:
        CF_USERNAME: ${{ inputs.cf_username }}
        CF_PASSWORD: ${{ inputs.cf_password }}
      run: |
        cf login -a ${{ inputs.cf_api }} -u $CF_USERNAME -p $CF_PASSWORD -o ${{ inputs.cf_org }} -s ${{ inputs.cf_space }}

    - name: "Run cf command"
      shell: bash
      working-directory: ${{ inputs.app_directory }}
      run: |
        [ "${{ inputs.full_command }}" = "push" ] && cf push --strategy rolling ${{ inputs.push_arguments }} || ${{ inputs.full_command }}
