name: "test deploy to cloud.gov"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Output cf version"
        uses: ./
        with:
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}
          full_command: "cf --version"

      - name: "Run push command"
        uses: ./
        env:
          CFSPACE: ${{ secrets.CF_SPACE }}
        with:
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}
          app_directory: ./test_site
          push_arguments: >-
            --vars-file deployment_config.yml
            --var cf_space="$CFSPACE"

      - name: "Run set-env command"
        uses: ./
        with:
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}
          full_command: "cf set-env cg-deploy-action DEPLOYED_SHA $GITHUB_SHA"
